### PR TITLE
string.c: convert case the way the string is read, not the way bytes are

### PR DESCRIPTION
**Pull request by takumin**
A build that reads a string as characters knew perfectly well that `"ÄÖÜ"` holds three characters, and still answered `"ÄÖÜ"` for their lower case. That is not a narrower answer than CRuby's, it is a wrong one: the string has a lower case and the method said it does not.

This gives core the Unicode case mappings, behind the define that already says a string is characters rather than bytes.

```ruby
"ÄÖÜ".downcase      #=> "äöü"
"ß".upcase          #=> "SS"
"ǳabc".capitalize   #=> "ǲabc"
"ßA".swapcase       #=> "SSa"
"ß".casecmp?("ss")  #=> true
```

### A build reading bytes is untouched

Each of the five methods keeps the ASCII loop it had and reaches the walk over characters only where the string holds one. A string of nothing but ASCII, and one read as bytes, hold no character the tables speak about, so a byte-indexed build answers what it always did and its `.text` does not move by a single byte.

A string that holds nothing but ASCII takes that loop on a character-indexed build too, and is read through once to find out where it has not been read through already. That is what the walk would do anyway, and doing it first is what spares an ASCII receiver the second string the walk builds beside it.

### What the methods answer

Every answer asserted in the tests was read off CRuby 4.0.6 first, including the ones that look like bugs.

| | |
| --- | --- |
| `"K".downcase` | `"k"`, three bytes down to one |
| `"İ".downcase` | `"i"` plus U+0307, one character up to two |
| `"ΣΟΦΟΣ".downcase` | `"σοφοσ"`, since word-final sigma reads its neighbours and CRuby does not apply it either |
| `"ﬁ".upcase` | `"FI"` |
| `"ı".upcase` | `"I"`, two bytes down to one |
| `"ǳ".capitalize` | `"ǲ"`, the title case rather than the upper case `"Ǳ"` |
| `"ა".upcase` / `"ა".capitalize` | `"Ა"` / `"ა"`, upper cased but not title cased |
| `"ǅ".swapcase` | `"dŽ"`, which neither of its cases spells |
| `"İ".casecmp?("i")` | `false`, since U+0130 folds to `"i"` plus U+0307 |
| `"\xC3ABC".downcase` | `ArgumentError: input string invalid` |

`casecmp` is the one case method that does not move. It orders strings by ASCII case in CRuby too, which is what makes `"ä".casecmp("Ä")` 1 while `"ä".casecmp?("Ä")` is true.

### The tables

`tools/gen_unicase.rb` generates `src/unicase.h` from the data the host CRuby carries. Three of the five hold a difference rather than a mapping, which is most of why they fit:

- **Title case** against upper case: 28 runs against the 195 it would take in full. The difference has to be able to say "this one does not change" as well, since `U+10D0` upper cases to `U+1C90` and title cases to itself, which a run of delta 0 stands for.
- **Swapping** against the rule that a character with a lower case swaps down and one without swaps up. The rule is right about every character but 31, all of them title case ones.
- **Folding** against the lowercase mapping. The two answer alike for all but 108 sources, so the difference is 24 runs where a table of its own would take 198.

A run is packed into six bytes rather than spelled as a struct of four fields, which costs twelve to the same effect: the fields are a 21-bit source, a 7-bit count, one bit of stride and a 17-bit delta, and over half of what the struct spends is padding around a codepoint sitting in a 32-bit field. A multi-character entry is five bytes the same way.

### Size

Measured on `ci/gcc-clang`, `.text` of `libmruby.a` against master:

| build | |
| --- | --- |
| `bintest` | +8,333 |
| `cxx_abi` | +8,789 |
| `full-debug` | +8,644 |
| `byte-string` | **0** |

Of the 8,333 on a character-indexed build, 2,598 is the runs, 1,300 the multi-character entries, 869 the pool they spell themselves in, 200 the table descriptors, and the rest the lookups and the walk.

### Verified

`MRUBY_CONFIG=ci/gcc-clang rake -m test`, all four builds and the bintests, KO 0, Crash 0 and Warning 0 on every commit of the branch.

## Summary by CodeRabbit

* **New Features**
  * UTF-8-enabled builds now support Unicode-aware `capitalize`, `downcase`, `upcase`, and `swapcase`, including multi-character mappings.
  * Added Unicode case folding through `casecmp?` for non-ASCII strings.
* **Bug Fixes**
  * Invalid UTF-8 sequences now raise `ArgumentError` during Unicode case conversion.
  * Binary and ASCII-only strings retain their existing byte-oriented behavior.
* **Documentation**
  * Clarified Unicode case conversion, folding behavior, multi-character results, and encoding-specific limitations.

### CODE REVIEW

File: doc/guides/mrbconf.md [hunk 1]
```diff
@@ -215,6 +215,11 @@ end
 `MRB_UTF8_STRING`
 
 - Adds UTF-8 encoding support to character-oriented String instance methods.
+- Case conversion follows Unicode: `String#downcase`, `#upcase`,
+  `#capitalize`, `#swapcase` and `#casecmp?` map every character Unicode gives
+  a case, a mapping may spell several characters (`"ß".upcase` is `"SS"`), and
+  a string holding bytes that spell no character is refused with
+  `ArgumentError`.
```
[the remark this answers is not in the document]
Comment (takumin) [reply doc/guides/mrbconf.md]: Done. The bullet now names the four conversions only, and says `String#casecmp?` folds by the same data rather than converting. A second bullet carries what is true of both: a string read as bytes converts and folds ASCII alone, and one holding bytes that spell no character is refused with `ArgumentError`.

File: tools/gen_unicase.rb [hunk 2]
```diff
@@ -0,0 +1,270 @@
...
+  ['fold',  fold_diff,  'where folding differs from the lowercase mapping'],
+]
+
+encoded = TABLES.map do |name, map, _|
+  runs = runs_of(map)
+  multi = multis_of(map).map { |cp, s| [cp, place.call(s), s.bytesize] }
+  [name, runs, multi]
+end
+
+widest = ([lower, upper, title, fold].flat_map { |m| m.values.map(&:bytesize) }).max
```
[the remark this answers is not in the document]
Comment (takumin) [reply tools/gen_unicase.rb]: Right that the swap table was missing, fixed, though not by tying `MAX_MULTI_LEN` to `widest`.

`widest` is derived from `TABLES` now, so it is measured over exactly the tables that get emitted rather than over a list beside them, and a table added there cannot be left out of it. That also puts the fix in the commit that added the swap table rather than at the end of the branch.

`MAX_MULTI_LEN` stays 7 because it is a different limit: 7 is the width of the `len` field a multi entry packs into three bits, not the size of the runtime buffer. An entry has to fit both, and once `widest` is measured over the emitted tables the buffer bound holds by construction, so comparing against `[widest, 7].min` would test the same data against itself. The value is still 6; the widest swap spelling is the 5 bytes of `U+1F88` to "ἀΙ".

**Comment by takumin** [comment]
The two nitpicks are in as well, both in the commit that introduced what they are about, and the branch is force-pushed.

**The ASCII fast path.** `mrb_str_case_convert_unicode` asked the coderange and took the walk whenever the answer was not already 7BIT, so a receiver holding nothing but ASCII whose coderange had not been recorded yet built a second string and replaced the buffer where the byte loop would have converted in place. It asks `str_ascii_p` now, which is the walk's own first pass rather than an extra one: reading the string through is what the conversion does anyway, and doing it first is what spares an ASCII receiver the string built beside it. The byte reading is asked about before it, since a string read as bytes must not come away recorded as holding one character per byte.

**The endless method definition.** Gone. `doc/guides/compile.md` and `doc/guides/getting-started.md` both put the floor at Ruby 2.5, and no other script in the tree uses the syntax.

Neither costs a byte-indexed build anything: `.text` there is still master's, byte for byte. The size table in the description is remeasured against master on the pushed branch, and every commit of it was built clean and tested (four builds and the bintests, KO 0, Crash 0, Warning 0).

**Comment by takumin** [comment]
Sorry, this needed a rebase and I did not catch it in time.

#7181 dropped `mrb_str_modify_keep_ascii()` after this branch was pushed, and the two calls this branch adds were left behind. Nothing here turned red: the rebase is clean as far as git is concerned, and the checks above were run against the master this branch was cut from. Merged as it stood, it would have broken the build with `implicit declaration of function 'mrb_str_modify_keep_ascii'` in both files.

Force pushed the rebase. The fix is folded into the two commits that introduce the calls rather than added on top, so every commit still builds and tests green on its own.

`mrb_str_case_convert_unicode()` now prepares with `str_modify_keep_cr()`. A string of nothing but ASCII goes back to the caller before this point, so the answer the old call was there to keep is already out of reach; `str_modify_keep_cr()` keeps VALID as well, which the old one did not.

`str_fold_ascii()` in mruby-string-ext prepares with `mrb_str_modify()`, since the internal one is not offered outside the library. It writes to a `mrb_str_dup()` that `String#casecmp?` compares byte for byte and then drops, so no one reads what the prepare leaves behind.

Checked each of the five commits with `full-core`, and the tip with `mruby-encoding` taken out of it as well.
