### PR TITLE
Fix #5175 - problem in c flags at gcc.rake

### LINKED ISSUE #5175: Array of array error in gcc.rake
Dear @shuujii,

I've got an error while trying to compile https://github.com/mruby-esp32/mruby-esp32.
I think this bug was introduced in be76cec3422ddedbfce48768db5aec004e2f0aee.
Basically `c_mandatory_flags` is an `Array` itself. Then `compiler.flags` will turn to be an Array of (Array|String).
Then when `gsub` is called on the `Array` it raises the error.
I've fixed it locally by just using `Array#flatten` like:

```diff
diff --git a/tasks/toolchains/gcc.rake b/tasks/toolchains/gcc.rake
index 316d2d9a..c38a608c 100644
--- a/tasks/toolchains/gcc.rake
+++ b/tasks/toolchains/gcc.rake
@@ -10,7 +10,7 @@ MRuby::Toolchain.new(:gcc) do |conf, params|
       compiler.flags = [ENV['CXXFLAGS'] || ENV['CFLAGS'] || compiler_flags]
     else
       compiler.command = ENV['CC'] || default_command
-      compiler.flags = [c_mandatory_flags, ENV['CFLAGS'] || [compiler_flags, cxx_invalid_flags, %w(-Wwrite-strings)]]
+      compiler.flags = [c_mandatory_flags, ENV['CFLAGS'] || [compiler_flags, cxx_invalid_flags, %w(-Wwrite-strings)]].flatten
     end
     compiler.option_include_path = %q[-I"%s"]
     compiler.option_define = '-D%s'
```

I'm issuing a PR now. Feel free to guide me to fix it in any other way you think it should be more appropriate.

The complete error message follows bellow.

```
$ make MRUBY_EXAMPLE=simplest_mrb.rb
Toolchain path: /Users/abinoam/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
Toolchain version: esp-2020r3
Compiler version: 8.4.0
Python requirements from /Users/abinoam/esp/esp-idf/requirements.txt are satisfied.

App "mruby_example" version: a08fb71-dirty
rake aborted!
NoMethodError: undefined method `gsub' for ["-std=gnu99"]:Array
/Users/abinoam/esp/mruby-esp32/components/mruby_component/esp32_build_config.rb:35:in `block (3 levels) in <top (required)>'
/Users/abinoam/esp/mruby-esp32/components/mruby_component/esp32_build_config.rb:35:in `collect!'
/Users/abinoam/esp/mruby-esp32/components/mruby_component/esp32_build_config.rb:35:in `block (2 levels) in <top (required)>'
(eval):1:in `cc'
/Users/abinoam/esp/mruby-esp32/components/mruby_component/esp32_build_config.rb:31:in `block in <top (required)>'
/Users/abinoam/esp/mruby-esp32/components/mruby_component/mruby/lib/mruby/build.rb:111:in `instance_eval'
/Users/abinoam/esp/mruby-esp32/components/mruby_component/mruby/lib/mruby/build.rb:111:in `initialize'
/Users/abinoam/esp/mruby-esp32/components/mruby_component/mruby/lib/mruby/build.rb:400:in `initialize'
/Users/abinoam/esp/mruby-esp32/components/mruby_component/esp32_build_config.rb:28:in `new'
/Users/abinoam/esp/mruby-esp32/components/mruby_component/esp32_build_config.rb:28:in `<top (required)>'
/Users/abinoam/esp/mruby-esp32/components/mruby_component/mruby/lib/mruby/build.rb:50:in `load'
/Users/abinoam/esp/mruby-esp32/components/mruby_component/mruby/lib/mruby/build.rb:50:in `load_config'
/Users/abinoam/esp/mruby-esp32/components/mruby_component/mruby/Rakefile:17:in `<top (required)>'
/Users/abinoam/.rvm/gems/ruby-2.6.3/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/Users/abinoam/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/Users/abinoam/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)
make[2]: *** [all] Error 1
make[1]: *** [build] Error 2
make: *** [component-mruby_component-build] Error 2
```

PS: Unfortunately the mruby-esp32 repo compiles only against 2.1.2 mruby version (because of other bugs). I'm trying to bisect and see if I can forward the mruby-esp32 repo into mruby master branch.

### PR DESCRIPTION
**Pull request by abinoam**
Fix #5175

### CODE REVIEW

**Comment by abinoam** [comment]
Closing as it was fixed at https://github.com/mruby-esp32/mruby-esp32/pull/20
