### ISSUE TITLE
mruby does not build with gperf 3.1

### ISSUE THREAD

**Issue by lopopolo** [mruby/mruby#4628]
See https://github.com/artichoke/artichoke/pull/169.

The generated prototype for `mrb_reserved_word` under gperf 3.1 is different than the prototype expected by `parse.y`:

```
In file included from /home/circleci/project/target/debug/build/mruby-sys-a3d94e2378717b5b/out/mruby-sys/vendor/mruby-bc7c5d3/mrbgems/mruby-compiler/core/parse.y:4692:
/home/circleci/project/target/debug/build/mruby-sys-a3d94e2378717b5b/out/mruby-sys/vendor/mruby-bc7c5d3/mrbgems/mruby-compiler/core/keywords:72:1: error: conflicting types for 'reserved_word'
mrb_reserved_word (register const char *str, register size_t len)
^
/home/circleci/project/target/debug/build/mruby-sys-a3d94e2378717b5b/out/mruby-sys/vendor/mruby-bc7c5d3/mrbgems/mruby-compiler/core/keywords:5:37: note: expanded from macro 'mrb_reserved_word'
#define mrb_reserved_word(str, len) reserved_word(str, len)
                                    ^
/home/circleci/project/target/debug/build/mruby-sys-a3d94e2378717b5b/out/mruby-sys/vendor/mruby-bc7c5d3/mrbgems/mruby-compiler/core/keywords:4:30: note: previous declaration is here
static const struct kwtable *reserved_word(const char *, unsigned int);
```

Here's an example [failing build](https://circleci.com/gh/artichoke/artichoke/1214?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

I think I started getting this failure when I upgraded my build container to Debian Buster which includes gperf 3.1.
