### ISSUE TITLE
mruby-array-ext fails to build with conf.enable_cxx_exception (C++ compiler required error)

### ISSUE THREAD

**Issue by buty4649** [mruby/mruby#6667]
mruby-array-ext fails to build when conf.enable_cxx_exception is enabled due to C/C++ compiler mismatch.

## Error Message

```
In file included from /path/to/mruby/mrbgems/mruby-array-ext/src/array.c:11:
/path/to/mruby/include/mruby/throw.h:26:3: error: #error "need to be compiled with C++ compiler"
   26 | # error "need to be compiled with C++ compiler"
      |   ^~~~~
```

## Reproduction Steps

array-ext.rb:
```ruby
MRuby::Build.new do |conf|
  conf.toolchain
  conf.gembox 'default'
  conf.enable_cxx_exception
end
```

build mruby:
```sh
$ CONFIG=array-ext.rb rake
-- snip --
In file included from /path/to/mruby/mrbgems/mruby-array-ext/src/array.c:11:
/path/to/mruby/include/mruby/throw.h:26:3: error: #error "need to be compiled with C++ compiler"
   26 | # error "need to be compiled with C++ compiler"
      |   ^~~~~
```

## Identified Problem Commit (via git bisect)

- Good: f4fb41b52 (kernel.c: regression on struct/array/hash == override with super; fix # 6660)
- Bad: b56293c41 (mruby-array-ext: fix memory leak in array set operations; ref # 6662)
