### ISSUE TITLE
strange NoMethodError

### ISSUE THREAD

**Issue by yyamano** [mruby/mruby#4140]
The following code doesn't work with latest mruby. I wonder why "f.x += 1" works, but "f.foo" doesn't.

I think this is the root cause of https://github.com/iij/mruby-mtest/issues/15.
Also  it probably related with https://github.com/mruby/mruby/issues/4137.

```
yyamano@boot-tron% cat -n foo.rb 
     1	class Foo
     2	  def initialize() @x = 0 end
     3	  def x() @x end
     4	  def x=(n) @x = n end
     5	  def foo() self.x += 1 end
     6	end
     7	
     8	f = Foo.new
     9	puts f.x += 1
    10  puts f.foo
```

```
yyamano@boot-tron% ./build/host/bin/mruby foo.rb 
1
trace (most recent call last):
	[0] foo.rb:10
	[1] foo.rb:5:in foo
foo.rb:5: undefined method 'x=' (NoMethodError)
```
It works fine with cruby 2.0.0 and mruby 1.4.1.

```
yyamano@boot-tron% ruby -v
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
yyamano@boot-tron% ruby foo.rb 
1
2
```

**Comment by matz** [comment]
It's fixed along with #4137
