### ISSUE TITLE
undefined method 'const_missing'

### ISSUE THREAD

**Issue by rpn** [mruby/mruby#3003]
```
# sample.rb
class A; end
a = A.new
class << a
  def foo; A.new; end
end
a.foo
```
```
>mruby sample.rb
trace:
        [1] sample.rb:5:in #<Class:0x828118>#foo
        [0] sample.rb:7
sample.rb:5: undefined method 'const_missing' for #<A:0x828118> (NoMethodError)
```
What am I doing wrong?

**Comment by cremno** [comment]
No, according to `git bisect` it was broken by #2521. Weirdly `rake test` succeeds if I revert the (presumably incorrect) changes to `src/vm.c`.

**Comment by cremno** [comment]
Oops, the tests didn't even run (they fail). I didn't know about `enable_test`.
