### ISSUE TITLE
weird `const_missing` exceptions in mrblib code (mruby 3.1.0 and above)

### ISSUE THREAD

**Issue by kazuho** [mruby/mruby#5725]
I've been trying to use mruby-require with the recent versions of mruby (see https://github.com/iij/mruby-require/pull/29) and have noticed one behavior that seems like an issue with mruby 3.1.0 and above.

When I run mruby-require of the PR linked above with mruby 3.0.0, everything works fine. But when I run it using mruby 3.1.0, a const_missing error is raised complaining that `File.exist?` cannot be found.

__Steps to reproduce:__
1. Checkout https://github.com/iij/mruby-require/pull/29.
2. Build mruby with the following configuration:
```ruby
MRuby::Build.new do |conf|
  conf.toolchain :gcc
  conf.gembox "default"
  conf.gem "mruby-require"
end
```
3. Run the following script using mruby being built:
```ruby
print "#{File.file?("/")}\n"
require "/nonexistent"
```
When I run this script using mruby 3.0.0 being built, the first line emits "false" (because `/` is a directory), then complains that `/nonexistent` cannot be loaded. Fine.
But when I run this script using mruby 3.1.0 being built, it raises a const_missing exception [here](https://github.com/iij/mruby-require/blob/5afbed21d2cf6e8f0c75fa9d4e0397a8ff893d32/mrblib/require.rb#L47).

__Why I think this is a bug of mruby:__

While this error is related to mruby-require, I'm reporting it here because I suspect this is a problem of mruby, due to the following reasons:
* the version of mruby-require being used does not have external dependency outside of mrbgems bundled by mruby
* the "gem_init" function of mruby-require just calls `mrb_define_method` and does nothing else, the problem that we see seems to happen before any logic of mruby-require written in C is being invoked

Therefore, I'm suspecting if there's an issue with the ruby code found in mrbgems having issues with accessing constants defined in other mrbgems.

**Comment by kazuho** [comment]
Did a bisect, it seems that this is a regression caused by #5272.

**Comment by kazuho** [comment]
@matz Of course. Thank you for looking into the issue.

When I run the ruby script above, I get:
```
% build/host/bin/mruby ~/tmp/defect.rb       
false
trace (most recent call last):
	[5] /Users/kazuho/tmp/defect.rb:2
	[4] /Users/kazuho/mydev/3p/mruby-require/mrblib/require.rb:40:in require
	[3] /Users/kazuho/mydev/3p/mruby/mrblib/enum.rb:78:in find
	[2] /Users/kazuho/mydev/3p/mruby/mrblib/array.rb:17:in each
	[1] /Users/kazuho/mydev/3p/mruby/mrblib/enum.rb:79:in detect
/Users/kazuho/mydev/3p/mruby-require/mrblib/require.rb:41:in require: undefined method 'const_missing' (NoMethodError)
```

And in fact, I've just found out that if I override `const_missing` and return the correct object,
```ruby
module Kernel
  def const_missing(id)
    File
  end
end
print "#{File.file?("/")}\n"
require "/nonexistent"
```
then things work as expected:
```
% build/host/bin/mruby ~/tmp/defect.rb
false
trace (most recent call last):
	[1] /Users/kazuho/tmp/defect.rb:7
/Users/kazuho/mydev/3p/mruby-require/mrblib/require.rb:54:in require: cannot load such file -- /nonexistent (LoadError)
```

Therefore I think it could be the case that the script being loaded from mrblib is somehow not accessing the correct `File` object.

**Comment by kazuho** [comment]
Than you very much for the quick response! I'm afraid that the problem is still not fully fixed.

92be161 indeed is an improvement, I believe it fixes a TypeError that was raised at https://github.com/iij/mruby-require/blob/master/mrblib/require.rb#L6. FWIW, IIRC we started seeing this TypeError in mruby 3.0.0. I actually had a workaround for this, which simply removed the code for simplicity (https://github.com/iij/mruby-require/pull/29/commits/03fe79f044c3529ffc47646d0080f33e2d84d225).

However, that is not the only problem. Even with 92be161, I am still seeing a `const_missing` exception being raised at https://github.com/iij/mruby-require/blob/master/mrblib/require.rb#L51, i.e.:
```ruby
    if ['/', '.'].include? path[0]
      path0 = filenames.find do |fname|
        File.file?(fname)    <--- HERE
      end
```

When doing git bisect, I know that 2d8f4fa introduced this problem. I anticipate that this problem could also be related to Proc, because we invoke `File.extname` just before entering this if and do block without having a problem (see https://github.com/iij/mruby-require/blob/master/mrblib/require.rb#L40).

I would appreciate it if you could take a look.

**Comment by dearblue** [comment]
The problem with `#const_missing` no longer exists after applying either of the following patches.

  - ```diff
    diff --git a/include/mruby/proc.h b/include/mruby/proc.h
    index 9d197f48a..4f55c6ee6 100644
    --- a/include/mruby/proc.h
    +++ b/include/mruby/proc.h
    @@ -70,7 +70,7 @@ struct RProc {
     #define MRB_PROC_ENVSET 1024
     #define MRB_PROC_ENV_P(p) (((p)->flags & MRB_PROC_ENVSET) != 0)
     #define MRB_PROC_ENV(p) (MRB_PROC_ENV_P(p) ? (p)->e.env : NULL)
    -#define MRB_PROC_TARGET_CLASS(p) (MRB_PROC_ENV_P(p) ? (p)->e.env->c : (p)->e.target_class)
    +#define MRB_PROC_TARGET_CLASS(p) (MRB_PROC_ENV_P(p) ? (p)->e.env->c : (p)->e.target_class ? (p)->e.target_class : mrb->object_class)
     #define MRB_PROC_SET_TARGET_CLASS(p,tc) do {\
       if (MRB_PROC_ENV_P(p)) {\
         (p)->e.env->c = (tc);\
    ```

  - ```diff
    diff --git a/src/variable.c b/src/variable.c
    index 68d3a388d..38d35f636 100644
    --- a/src/variable.c
    +++ b/src/variable.c
    @@ -828,6 +828,7 @@ mrb_vm_const_get(mrb_state *mrb, mrb_sym sym)
       proc = proc->upper;
       while (proc) {
         c2 = MRB_PROC_TARGET_CLASS(proc);
    +    if (!c2) c2 = mrb->object_class;
         if (c2 && iv_get(mrb, c2->iv, sym, &v)) {
           return v;
         }
    ```

I am currently checking to see which is preferred or if there are other good methods.

**Comment by dearblue** [comment]
I don't think this is very desirable, but for reference.
Disabling presym with `MRuby::Build#disable_presym` in build_config seems to work on mruby-3.1.0.

**Comment by kazuho** [comment]
Thank you for the fix! Confirmed as of dc8da16 that the issue no longer exists.
