### ISSUE TITLE
Array of array error in gcc.rake

### ISSUE THREAD

**Issue by abinoam** [mruby/mruby#5175]
Dear @shuujii,

I've got an error while trying to compile https://github.com/mruby-esp32/mruby-esp32.
I think this bug was introduced in be76cec3422ddedbfce48768db5aec004e2f0aee.
Basically `c_mandatory_flags` is an `Array` itself. Then `compiler.flags` will turn to be an Array of (Array|String).
Then when `gsub` is called on the `Array` it raises the error.
I've fixed it locally by just using `Array#flatten` like:

```diff
diff --git a/tasks/toolchains/gcc.rake b/tasks/toolchains/gcc.rake
index 316d2d9a..c38a608c 100644
--- a/tasks/toolchains/gcc.rake
+++ b/tasks/toolchains/gcc.rake
@@ -10,7 +10,7 @@ MRuby::Toolchain.new(:gcc) do |conf, params|
       compiler.flags = [ENV['CXXFLAGS'] || ENV['CFLAGS'] || compiler_flags]
     else
       compiler.command = ENV['CC'] || default_command
-      compiler.flags = [c_mandatory_flags, ENV['CFLAGS'] || [compiler_flags, cxx_invalid_flags, %w(-Wwrite-strings)]]
+      compiler.flags = [c_mandatory_flags, ENV['CFLAGS'] || [compiler_flags, cxx_invalid_flags, %w(-Wwrite-strings)]].flatten
     end
     compiler.option_include_path = %q[-I"%s"]
     compiler.option_define = '-D%s'
```

I'm issuing a PR now. Feel free to guide me to fix it in any other way you think it should be more appropriate.

The complete error message follows bellow.

```
$ make MRUBY_EXAMPLE=simplest_mrb.rb
Toolchain path: /Users/abinoam/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
Toolchain version: esp-2020r3
Compiler version: 8.4.0
Python requirements from /Users/abinoam/esp/esp-idf/requirements.txt are satisfied.

App "mruby_example" version: a08fb71-dirty
rake aborted!
NoMethodError: undefined method `gsub' for ["-std=gnu99"]:Array
/Users/abinoam/esp/mruby-esp32/components/mruby_component/esp32_build_config.rb:35:in `block (3 levels) in <top (required)>'
/Users/abinoam/esp/mruby-esp32/components/mruby_component/esp32_build_config.rb:35:in `collect!'
/Users/abinoam/esp/mruby-esp32/components/mruby_component/esp32_build_config.rb:35:in `block (2 levels) in <top (required)>'
(eval):1:in `cc'
/Users/abinoam/esp/mruby-esp32/components/mruby_component/esp32_build_config.rb:31:in `block in <top (required)>'
/Users/abinoam/esp/mruby-esp32/components/mruby_component/mruby/lib/mruby/build.rb:111:in `instance_eval'
/Users/abinoam/esp/mruby-esp32/components/mruby_component/mruby/lib/mruby/build.rb:111:in `initialize'
/Users/abinoam/esp/mruby-esp32/components/mruby_component/mruby/lib/mruby/build.rb:400:in `initialize'
/Users/abinoam/esp/mruby-esp32/components/mruby_component/esp32_build_config.rb:28:in `new'
/Users/abinoam/esp/mruby-esp32/components/mruby_component/esp32_build_config.rb:28:in `<top (required)>'
/Users/abinoam/esp/mruby-esp32/components/mruby_component/mruby/lib/mruby/build.rb:50:in `load'
/Users/abinoam/esp/mruby-esp32/components/mruby_component/mruby/lib/mruby/build.rb:50:in `load_config'
/Users/abinoam/esp/mruby-esp32/components/mruby_component/mruby/Rakefile:17:in `<top (required)>'
/Users/abinoam/.rvm/gems/ruby-2.6.3/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/Users/abinoam/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/Users/abinoam/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)
make[2]: *** [all] Error 1
make[1]: *** [build] Error 2
make: *** [component-mruby_component-build] Error 2
```

PS: Unfortunately the mruby-esp32 repo compiles only against 2.1.2 mruby version (because of other bugs). I'm trying to bisect and see if I can forward the mruby-esp32 repo into mruby master branch.

**Comment by shuujii** [comment]
Thank you for your report.

Originally nested array (and probably string) as the value of `compiler.flags` are also allowed. It seems that mruby-esp32 also sets a nested array.

https://github.com/mruby-esp32/mruby-esp32/blob/a08fb71d1e5dd13ee755efa4dacc53fb17625152/components/mruby_component/esp32_build_config.rb#L9-L12

Therefore, if anything, it seems to be an issue with mruby-esp32 that they are not taken into account.

However, I think the proposed change may be applied for compatibility. When applying, I think it's better to have a flat array regardless of the result of `if compiler == conf.cxx`.

**Comment by abinoam** [comment]
You're right about the problem in `esp32_build_config.rb` from `mruby-esp32`.
I'll try to open a PR there too.
If you take a closer look we will find other places that may be affected in some situations like 
```ruby
linker.flags = [ENV['LDFLAGS'] || %w()]
```
at https://github.com/mruby/mruby/blob/master/tasks/toolchains/gcc.rake#L25

Perhaps I should stop and try to find every possible place and solve it in a more global way.

Perhaps we should use more the Binary OR Operator (`|`) .
```ruby
c_mandatory_flags = %w(-std=gnu99) # => ["-std=gnu99"]
cxx_invalid_flags = %w(-Werror-implicit-function-declaration) # => ["-Werror-implicit-function-declaration"]
flags = c_mandatory_flags | cxx_invalid_flags # => ["-std=gnu99", "-Werror-implicit-function-declaration"]
```

Feel free to give any further suggestions, details. I'll try to think a little more about it meantime.

**Comment by abinoam** [comment]
Hi @shuujii,

> Originally nested array (and probably string) as the value of compiler.flags are also allowed. 

Do you mean `mruby` itself doesn't care if it's Array or String as the elements of the flags Array?

If so, now I can see that it's `mruby-esp32` that triggers the error when it tries to `gsub` some flag.
Basically `mruby-esp32` is expecting an Array of Strings only (without Arrays inside). (But mruby currently doesn't guarantees that).

```ruby
 cc.flags.collect! { |x| x.gsub('-MP', '') }
```

[esp32_build_config](https://github.com/mruby-esp32/mruby-esp32/blob/a08fb71d1e5dd13ee755efa4dacc53fb17625152/components/mruby_component/esp32_build_config.rb#L35)

I'll try to read more of the mruby code to try to understand how it handles the Array(Array|String).

**Comment by abinoam** [comment]
I see that [MRuby:::Command::Compiler](https://github.com/mruby/mruby/blob/master/lib/mruby/build/command.rb#L76) uses `flatten` all over to guarantee that it may receive `Array(Array|String)`.

So perhaps I should close this issue and PR and open another one at `mruby-esp32` to change that line that tries to gsub the default flags.

What do you think about it @shuujii ?

**Comment by abinoam** [comment]
I've just opened and issue and PR at `mruby-esp32`

https://github.com/mruby-esp32/mruby-esp32/issues/19
https://github.com/mruby-esp32/mruby-esp32/pull/20

**Comment by shuujii** [comment]
> I see that [MRuby:::Command::Compiler](https://github.com/mruby/mruby/blob/master/lib/mruby/build/command.rb#L76) uses `flatten` all over to guarantee that it may receive `Array(Array|String)`.

The code looks like `[flags].flatten`, so It also seems to be acceptable if `flags` is `String` (I'm not sure if it's intentional).

> open another one at `mruby-esp32` to change that line that tries to gsub the default flags.

Essentially, I think it's better to fix `mruby-esp32`. Personally, I think you can also fix `gcc.rake` for compatibility (I don't have the authority, but I think the fix will be merged).

I don't think it's so important how to make a flat array, so I think any method will do.

* `[*flags1, *flags2, *flags3]`
* `[flags1, flags2, flags3].flatten`
* `flags1.dup.concat(flags2).concat(flags3)`

You can use `Array#|` if you want to eliminate duplication, but I don't think it's necessary in `gcc.rake`.

> ```ruby
> linker.flags = [ENV['LDFLAGS'] || %w()]
> ```

This can be fixed with `linker.flags = [*ENV['LDFLAGS']]`.

**Comment by abinoam** [comment]
Hi @shuujii 

I think I'm closing issue and pr we could fix it at `mruby-esp32` repo with (https://github.com/mruby-esp32/mruby-esp32/pull/20) that @pandax381 has already merged.

Thanks for your assistance and comments.
