### ISSUE TITLE
Unary minus seems broken

### ISSUE THREAD

**Issue by catsidhe** [mruby/mruby#6210]
Strange unary minus behavior that also prevents overriding it.

```ruby
> -nil
undefined method '-@' (NoMethodError)
> -nil; nil
 => nil # this doesn't seem OK
> +nil; nil
undefined method '+@' (NoMethodError)
> class Foo; def -@; p 'bar'; end; end; -Foo.new; nil
 => nil # doesn't print "bar" 
```
e42f192827102a6aa7a398d0360e310ed2ae20d2 is the first bad commit

**Comment by matz** [comment]
Thank you for the report.
